language: python
python:
    - "2.7"

sudo: required
cache:
    directories:
        - "~/.platformio"
        
branches:
  only:
    - master
    
addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1
    
before_script:
  - wget https://github.com/Infineon/Assets/releases/download/current/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.-d-.tar.bz2 -O /tmp/gcc-arm-none-eabi.tar.bz2
  - tar -xjf /tmp/gcc-arm-none-eabi.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_4-2016q3/bin/

env:
    global:
        - USR_NAME="Sun Yuxi (IFAG DES SDF FW)"
        - USR_EMAIL="Yuxi.Sun@infineon.com"
        - secure: 1SbBRVOZZSul8qllkZIkW6kNByLpINA6AaicQed7xu/rdjmZo1fiBk5s1gkrcS2xZr3+a2TBNba1Fp/qQEnHgDyuXj5rxtjM0VCD7wdCrhl+y9iKtYaznTPr/jAo6AU7GS4nIV4Yessn83owr2WFLSugss611RbzMW0rhQFzbiv7cFbOxX2pvytmN0PdHllAa4etjOB/HlIq0AVGQAS4dCgcvErdE90MZtg04eq+gvNxZgrbxkfm/RUEiRFDfdYdVxcOMo7DdiNWYt0r1TV+2whHbfNrTWlGSleZwtUDiYHwBOrDcah2CgQ8wYyDGLWUQrbmZ5MNt143gGzXhJsrP73pIxTkKIyvaeXX9br/M1SeUoW/jqSE8X5l8rbkOQHOF5PCDr8Tzkio18O3K9RW5Zn8VA9iZdizkI1QF/jfIWwIk8VbJjbNsLZijObDWzkezgtpyWPteK28lw/8l6XP0Tf+nOgT/CrkjppJcwTU8QQuMbYpeBq+BGYLp1fymG59iKKQNbckt/AzeYxoKDw0vtiuLZgDuxD9SO5QEbXr5lxQi3tO6arrlDhrxH+E5AO/0NdgdYorc5m3EYmHhMQI1He4SoceIN0F4+9EMzDbTEDZmP2pfj9i18aV+m5iFDls7r66tWYSchzUeEibBIrVLhJOgO3zXen9F928fb8YBuo=
    matrix:
        - PLATFORMIO_CI_SRC=examples/Cartesian 
        - PLATFORMIO_CI_SRC=examples/Cartesian_low_power 
        - PLATFORMIO_CI_SRC=examples/sine_generator 

install:
    ## build with stable core
    # - git clone https://github.com/Infineon/platformio-infineonxmc.git /tmp/builder
    # - pip install -U platformio
    # - platformio platform install -f file:///tmp/builder/. --without-package=uploader

    # build with development version
    - git clone https://github.com/Infineon/XMC-for-Arduino.git /tmp/core
    - zip -r /tmp/core/framework-arduinoxmc.zip /tmp/core/arm  
    - git clone https://github.com/Infineon/platformio-infineonxmc.git /tmp/builder
    - cd /tmp/builder
    - platform_json=$(<platform.json)
    - rm platform.json
    - jq '.packages."framework-arduinoxmc".version = "file:///tmp/core/framework-arduinoxmc.zip"' <<<"$platform_json" > platform.json
    - pip install -U platformio
    - platformio platform install -f file://. --without-package=uploader
    - cd -
script:
    - platformio ci --lib="." --board=xmc1100_xmc2go

after_success:
    # only build once (after one job by checking id, however this does not work reliably)
    - |
      if [ $(($TRAVIS_JOB_ID - $TRAVIS_BUILD_ID)) -eq 2 ]; then
        export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
        git clone https://github.com/Infineon/well-automated-documentation.git
        cd well-automated-documentation/docs
        # cd $TRAVIS_BUILD_DIR/docs
        chmod +x publish_pdf.sh
        ./publish_pdf.sh
      fi